### PR TITLE
Feature/#28 name change

### PR DESCRIPTION
**Pull request by geerdink**

### CODE REVIEW

**Comment by ruud** [comment]
Nice name :)
+1 for merging this branche

**Comment by ruud** [comment]
Some other changes on top of "name change" with be merge too.

**Comment by TimSoethout** [comment]
+1 to change the name. Or close this PR if is already done. :)

**Comment by TimSoethout** [comment]
I will try to pick this up tomorrow. Probably it's easier to redo the rename from scratch instead of trying to merge.

**Comment by TimSoethout** [comment]
Closed, because we will redo it.

**Pull request closed without merging**
